### ISSUE TITLE
Provide with interface

### ISSUE THREAD

**Issue by keiosweb** [VaclavObornik/di-ts#6]
Hi Vaclav,

Is it possible to configure DI to use TypeScript's interfaces? Right now when my class demands dependency specified by interface and I have a concrete class implementing that interface, I can't simply annotate my concrete class with @Provide(Interface), since TS won't recognize interface as valid argument for decorator:

http://i.keios.eu/snapshot-20150801-110807.png

This ends with: Error:(7, 10) TS2304: Cannot find name 'Interface'.

**Comment by VaclavObornik** [comment]
Hi!

I think it's not possible to use interfaces because, TypeScript is not emitting any info to the generated code about them.

**Comment by keiosweb** [comment]
I was thinking that maybe you could allow passing FQCNs as strings into @Provide, but haven't really looked into it, as I don't have the time right now. 

I went with abstract base classes (sort of - all methods simply throw errors in implementations, that way method can have proper type and still break if I forget to override it :smile:). With ABC's I can annotate concrete classes with @Provide for ABC this class extends and DI works very nicely, thanks for this! :+1: 

For anyone looking for this later - this is how I solved this:

```
class AbstractBaseClass {
    public saySomething(what:string):void {
        throw new Error('Abstract');
    }
}

@Provide(AbstractBaseClass)
class ConcreteClass extends AbstractBaseClass {
    public saySomething(what:string):void {
        console.info(what);
    }
}

@Inject
class CompositeClass {
    public constructor(private dependency:AbstractBaseClass) {}

    public test():void {
        this.dependency.saySomething('concrete injected in place of its abc');
    }
}
```
